linters:
  disable-all: true
  enable:
    - asciicheck
    - deadcode
    - depguard
    - dupl
    - errcheck
    - errorlint
    - exhaustive
    - exportloopref
    - forbidigo
    - forcetypeassert
    - gci
    - gocognit
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofumpt
    - goimports
    - goprintffuncname
    - gosimple
    - govet
    - importas
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - predeclared
    - revive
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - wastedassign
    - whitespace

linters-settings:
  depguard:
    list-type: whitelist
    packages:
      - github.com/mmcloughlin/ssarules
      - github.com/google

  exhaustive:
    default-signifies-exhaustive: true

  gci:
    local-prefixes: github.com/mmcloughlin/ssarules

  importas:
    no-unaliased: true
    alias:
      - pkg: go/(\w+)
        alias: go$1

issues:
  # Use exclude list while in development.
  exclude-use-default: true
  exclude-rules:
    - linters:
        - revive
      text: "should have comment or be unexported"
    - linters:
        - revive
      text: "comment on exported type"
